# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5734110983d05e3a5dcc1f954707d60dcff79a237d5c7d088719e347f687b92d678f5f9f10d64b6199110b4f2ee0e046162b11e188e46523fd26fd3102688703

test:
  secret_key_base: 27d1ac8f8ccf8ffea8b894048c044851d8b5e68f90d5be1043c3bc2b71ace97ffb9e3cf756d58fb8f377348a9e50c3cf1fd517082467a5ed8057b55cb0124531

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
